name: Continuous Integration
on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.4.2'

      - name: Install dependencies
        run: npm install

      - name: Lint the code
        run: npm run lint

      - name: Run unit test
        run: npm run test
